export interface Quote {
  text: string;
  author: string;
  es: string;
}

export const QUOTES: Quote[] = [
  { text: "The unexamined life is not worth living.", author: "Socrates", es: "Una vida sin examen no merece ser vivida." },
  { text: "We suffer more often in imagination than in reality.", author: "Seneca", es: "Sufrimos más en la imaginación que en la realidad." },
  { text: "The soul becomes dyed with the colour of its thoughts.", author: "Marcus Aurelius", es: "El alma se tiñe del color de sus pensamientos." },
  { text: "No man is free who is not master of himself.", author: "Epictetus", es: "No es libre quien no es dueño de sí mismo." },
  { text: "Knowing yourself is the beginning of all wisdom.", author: "Aristotle", es: "Conocerse a uno mismo es el principio de toda sabiduría." },
  { text: "The only true wisdom is in knowing you know nothing.", author: "Socrates", es: "La única verdadera sabiduría es saber que no sabes nada." },
  { text: "It is not that we have a short time to live, but that we waste a great deal of it.", author: "Seneca", es: "No es que tengamos poco tiempo, sino que perdemos mucho." },
  { text: "Happiness depends upon ourselves.", author: "Aristotle", es: "La felicidad depende de nosotros mismos." },
  { text: "Man is the measure of all things.", author: "Protagoras", es: "El hombre es la medida de todas las cosas." },
  { text: "The mind is everything. What you think you become.", author: "Buddha", es: "La mente lo es todo. En lo que piensas, te conviertes." },
  { text: "He who has a why to live can bear almost any how.", author: "Nietzsche", es: "Quien tiene un porqué para vivir puede soportar casi cualquier cómo." },
  { text: "The way to do is to be.", author: "Lao Tzu", es: "El camino del hacer es ser." },
  { text: "Everything flows.", author: "Heraclitus", es: "Todo fluye." },
  { text: "Waste no more time arguing about what a good man should be. Be one.", author: "Marcus Aurelius", es: "No pierdas más tiempo discutiendo qué debe ser un buen hombre. Sé uno." },
  { text: "It is the mark of an educated mind to be able to entertain a thought without accepting it.", author: "Aristotle", es: "Es propio de una mente educada poder considerar un pensamiento sin aceptarlo." },
  { text: "The impediment to action advances action. What stands in the way becomes the way.", author: "Marcus Aurelius", es: "El obstáculo en el camino se convierte en el camino." },
  { text: "Man is condemned to be free.", author: "Jean-Paul Sartre", es: "El hombre está condenado a ser libre." },
  { text: "One cannot step twice in the same river.", author: "Heraclitus", es: "Nadie se baña dos veces en el mismo río." },
  { text: "The happiness of your life depends upon the quality of your thoughts.", author: "Marcus Aurelius", es: "La felicidad de tu vida depende de la calidad de tus pensamientos." },
  { text: "To be is to be perceived.", author: "George Berkeley", es: "Ser es ser percibido." },
  { text: "Liberty consists in doing what one desires.", author: "John Stuart Mill", es: "La libertad consiste en hacer lo que uno desea." },
  { text: "The life of money-making is one undertaken under compulsion, and wealth is evidently not the good we are seeking.", author: "Aristotle", es: "La vida dedicada a hacer dinero se emprende por obligación, y la riqueza no es el bien que buscamos." },
  { text: "Begin at once to live, and count each separate day as a separate life.", author: "Seneca", es: "Empieza a vivir de inmediato y cuenta cada día como una vida separada." },
  { text: "In the depth of winter, I finally learned that within me there lay an invincible summer.", author: "Albert Camus", es: "En lo más profundo del invierno, finalmente aprendí que dentro de mí había un verano invencible." },
  { text: "The secret of happiness, you see, is not found in seeking more, but in developing the capacity to enjoy less.", author: "Socrates", es: "El secreto de la felicidad no está en buscar más, sino en desarrollar la capacidad de disfrutar con menos." },
  { text: "A man who dares to waste one hour of time has not discovered the value of life.", author: "Charles Darwin", es: "Un hombre que se atreve a desperdiciar una hora no ha descubierto el valor de la vida." },
  { text: "If you are distressed by anything external, the pain is not due to the thing itself, but to your estimate of it.", author: "Marcus Aurelius", es: "Si algo externo te angustia, el dolor no se debe a la cosa en sí, sino a tu valoración de ella." },
  { text: "The soul that sees beauty may sometimes walk alone.", author: "Goethe", es: "El alma que ve la belleza a veces camina sola." },
  { text: "To live is the rarest thing in the world. Most people exist, that is all.", author: "Oscar Wilde", es: "Vivir es lo más raro del mundo. La mayoría de la gente solo existe." },
  { text: "He who fears death will never do anything worthy of a living man.", author: "Seneca", es: "Quien teme a la muerte nunca hará nada digno de un hombre vivo." },
  { text: "The only thing I know is that I know nothing.", author: "Socrates", es: "Solo sé que no sé nada." },
  { text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Aristotle", es: "Somos lo que hacemos repetidamente. La excelencia no es un acto, sino un hábito." },
  { text: "The mind that is anxious about future events is miserable.", author: "Seneca", es: "La mente que se preocupa por el futuro es miserable." },
  { text: "Thou shouldst eat to live; not live to eat.", author: "Socrates", es: "Debes comer para vivir, no vivir para comer." },
  { text: "A journey of a thousand miles begins with a single step.", author: "Lao Tzu", es: "Un viaje de mil millas comienza con un solo paso." },
  { text: "The world is full of magical things patiently waiting for our wits to grow sharper.", author: "Bertrand Russell", es: "El mundo está lleno de cosas mágicas esperando pacientemente a que nuestro ingenio se agudice." },
  { text: "What we achieve inwardly will change outer reality.", author: "Plutarch", es: "Lo que logremos internamente cambiará la realidad exterior." },
  { text: "The greatest wealth is to live content with little.", author: "Plato", es: "La mayor riqueza es vivir contento con poco." },
  { text: "Be tolerant with others and strict with yourself.", author: "Marcus Aurelius", es: "Sé tolerante con los demás y estricto contigo mismo." },
  { text: "Nothing exists except atoms and empty space; everything else is opinion.", author: "Democritus", es: "Nada existe excepto átomos y espacio vacío; todo lo demás es opinión." },
  { text: "The measure of a man is what he does with power.", author: "Plato", es: "La medida de un hombre es lo que hace con el poder." },
  { text: "He is a wise man who does not grieve for the things which he has not, but rejoices for those which he has.", author: "Epictetus", es: "Es sabio quien no se lamenta por lo que no tiene, sino que se alegra por lo que tiene." },
  { text: "One must imagine Sisyphus happy.", author: "Albert Camus", es: "Hay que imaginar a Sísifo feliz." },
  { text: "The soul is healed by being with children.", author: "Dostoevsky", es: "El alma se cura estando con niños." },
  { text: "To find yourself, think for yourself.", author: "Socrates", es: "Para encontrarte a ti mismo, piensa por ti mismo." },
  { text: "All things are ready, if our minds be so.", author: "Shakespeare", es: "Todo está listo, si nuestra mente lo está." },
  { text: "That which does not kill us makes us stronger.", author: "Nietzsche", es: "Lo que no nos mata nos hace más fuertes." },
  { text: "I think therefore I am.", author: "Descartes", es: "Pienso, luego existo." },
  { text: "The wound is the place where the light enters you.", author: "Rumi", es: "La herida es el lugar por donde la luz entra en ti." },
  { text: "Do not spoil what you have by desiring what you have not.", author: "Epicurus", es: "No arruines lo que tienes deseando lo que no tienes." },
];
